### PR TITLE
feat: lint configuration changed to scan JS files too

### LINKED ISSUE #349: Check .js files with ESLint
Currently, ESLint only checks `.ts` files:

https://github.com/helmetjs/helmet/blob/de66579e4e43c0239c3caae37b5005b0eece4df8/package.json#L47

However, it should also check the small number of `.js` files in the project. (None of these files are published.) When we're all done, the command should probably look like this:

```json
 "lint:eslint": "eslint .", 
```

Because ESLint is currently configured for TypeScript, we may need to do some overrides.

### PR DESCRIPTION
**Pull request by njmulsqb**
Fixes #349

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! I'll take a look at this soon.

Just to double-check: what happens if you introduce a lint error in a .js file in the `bin` folder?

**Comment by njmulsqb** [comment]
> Thanks! I'll take a look at this soon.
> 
> Just to double-check: what happens if you introduce a lint error in a .js file in the `bin` folder?

I have introduced a unused variable error in one file in `bin` then `npm run lint` throws error

**Comment by EvanHahn** [comment]
Great! I plan to review in the next few days.

**Review by EvanHahn — APPROVED** [review]
Looks great! Thanks.

Feel free to [add yourself to the contributors list](https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md) if you like!

**Comment by njmulsqb** [comment]
> Looks great! Thanks.
> 
> Feel free to [add yourself to the contributors list](https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md) if you like!

I am up for open source work on this project, currently issue seems more to be feedback oriented or they require information. If you come across some coding related work dont hesitate to ping me.

Thanks

**Comment by EvanHahn** [comment]
Will do! Thanks again.

**Pull request merged**
