### PR TITLE
updating packages

### PR DESCRIPTION
**Pull request by y0y0z**

### CODE REVIEW

**Comment by y0y0z** [comment]
@EvanHahn: i created this pull-request to push approved [changes across submodules](https://github.com/helmetjs/feature-policy/pull/8)

**Comment by y0y0z** [comment]
@EvanHahn:
i am interested in all of them, but couldn't pass by without contributing back; and there's no need to apologies :)

may i ask why won't we just bump the major version of those packges with breaking changes?

**Comment by EvanHahn** [comment]
We could do that. But any breaking changes would "propagate" to this top-level packages, which we can't do—it doesn't matter what the version number is.

**Comment by y0y0z** [comment]
@EvanHahn: would you please share a link\elaborate shortly what are the breaking changes?

**Comment by EvanHahn** [comment]
The main breaking change: these subpackages require Node 8+, where Helmet requires Node 4+. This could cause errors on installation, or other unexpected errors.

I'm planning on releasing Helmet 4 later this month or in May, so we should be able to solve this soon.

**Pull request closed without merging**
