### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by mobinni**
When copy pasting this code it broke with a trailing comma and not comma for reportURI.

### CODE REVIEW

**Comment by EvanHahn** [comment]
Good catch! Thanks.

**Comment by EvanHahn** [comment]
@mobinni I'm making a new website for Helmet.js and I want to credit everyone who's contributed. Do you have a name and/or website you'd like me to use to credit you?

**Comment by mobinni** [comment]
Hey Evan

That's great! I currently don't have a website. My name is Mo Binni and you could link my twitter handle @mobinni.

Thanks very much

Regards
Mo Binni

**Comment by EvanHahn** [comment]
Will do!

**Pull request merged**
