### PR TITLE
change badge to svg

### PR DESCRIPTION
**Pull request by a0viedo**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Perfect! Thank you.

If you'd like to spend the time to go through [the other repos](https://github.com/helmetjs), I'd really appreciate it, but don't feel like you have to.

**Comment by EvanHahn** [comment]
@a0viedo I'm making a new website for Helmet.js and I want to credit everyone who's contributed. Do you have a name and/or website you'd like me to use to credit you?

**Comment by a0viedo** [comment]
@EvanHahn hey, thanks for asking! I'm ok with that, do you need any more info?

**Comment by EvanHahn** [comment]
A name and optional URL would be great.

**Comment by a0viedo** [comment]
Alejandro Oviedo and https://elendur.com/ is were I'm aiming to blog (failing hard rn)

**Comment by EvanHahn** [comment]
Will do! Stay tuned for the Helmet documentation website.

**Pull request merged**
