### PR TITLE
Release v4.0.0

### PR DESCRIPTION
**Pull request by EvanHahn**
**Planned release date: 2020-08-02**

Currently published: `helmet@4.0.0-rc.2`. Feedback welcome!

- [x] Additions
  - [x] Export TypeScript types (see #188, #209)
- [x] Changes
  - [x] Enable all middlewares by default
  - [x] `Content-Security-Policy`: add default value
  - [x] `Content-Security-Policy`: fail if duplicate directives are found
  - [x] `Content-Security-Policy`: fail if syntactically directive names/values are found
  - [x] `X-XSS-Protection` should be disabled by default (see #230)
  - [x] Move all submodules into this repo (internal-only change)
    - [x] `X-Download-Options` middleware (see #221)
    - [x] `Content-Security-Policy` middleware
    - [x] `Permitted-Cross-Domain-Policies` middleware
    - [x] `X-DNS-Prefetch-Control` middleware
    - [x] `Expect-CT` middleware
    - [x] `X-Frame-Options` middleware
    - [x] `X-Powered-By` middleware
    - [x] `Strict-Transport-Security` middleware
    - [x] `X-Content-Type-Options` middleware
    - [x] `Referrer-Policy` middleware
    - [x] `X-XSS-Protection` middleware
  - [x] Update documentation
- [x] Removals
  - [x] Drop support for old Node versions (see #146)
  - [x] Remove `helmet.hpkp` (see #180, #192)
  - [x] Remove `helmet.noCache` (see #215)
  - [x] Remove `helmet.featurePolicy`
  - [x] `Content-Security-Policy`: remove most checks
  - [x] `Content-Security-Policy`: remove functions as directive values
  - [x] `Content-Security-Policy`: remove `loose`
  - [x] `Content-Security-Policy`: remove `setAllHeaders`
  - [x] `Content-Security-Policy`: remove browser sniffing, including `disableAndroid` and `browserSniff` options (see https://github.com/helmetjs/csp/issues/97)
  - [x] `Strict-Transport-Security`: remove `setIf` (see #232)
  - [x] `Strict-Transport-Security`: remove `includeSubdomains` (lowercase "D") (see #231)
  - [x] `X-Frame-Options`: drop `ALLOW-FROM` support
  - [x] `X-Frame-Options`: drop `String` support
  - [x] `X-Powered-By`: remove `setTo` option (see #224)

### CODE REVIEW

**Comment by EvanHahn** [comment]
Just published `helmet@4.0.0-alpha.1`. I'd appreciate any feedback!

**Comment by benhjames** [comment]
These changes look fantastic @EvanHahn! I've just installed the alpha, all looks to be working so far.

**Comment by EvanHahn** [comment]
Just published `helmet@4.0.0-rc.1`, which you can install with `npm install helmet@next`. There have been no meaningful changes since `4.0.0-alpha.1` but some error messages were improved.

Planning to release this on Sunday, 2020-08-02 (a few days from now).

**Comment by EvanHahn** [comment]
Just published `helmet@4.0.0-rc.2`, which you can install with `npm install helmet@next`. Since `rc.1`, I have exported the `HelmetOptions` type, but nothing else has changed.

Still planning to release on Sunday.

**Pull request merged**
