### PR TITLE
Remove default export and provide named exports

### LINKED ISSUE #235: Issues with TypeScript imports in 4.0.0
Code like below overrides the exported object, which causes `default` being missing from every module.

```
module.exports = contentSecurityPolicy;
export default contentSecurityPolicy;
```

For example, inside `index.ts`, add `console.log("wat", expectCt);` under the import, and we'll see it's `undefined`.

### PR DESCRIPTION
**Pull request by sehrope**
# :bomb: **BREAKING** change...

This PR fixes #235 by removing the default export and replacing it with a named `helmet` export for the primary middleware creation function. Also adds individual named exports for the existing middleware functions. They can be imported via those exports or as properties of the primary middleware creation function.

Existing code that used default export or top level function export such as:

    // Default export style:
    import helmet from 'helmet';
    // Top level function
    import helmet = require('helmet');

Would need to be migrated to:

    // Import-style
    import { helmet } from 'helmet';
    // Using require:
    const { helmet } = require('helmet');

Code that previously imported individual middleware via a named import need not change:

    // This will continue to work:
    import { xssFilter } from 'helmet';
    // This will also continue to work:
    import { noSniff } = require('helmet');
    // And so will this:
    const { hsts } = require('helmet');

Here's what the dist package structure looks like:

```
$ node -p "require('./dist')"
{
  helmet: [Function: helmet] {
    contentSecurityPolicy: [Function: contentSecurityPolicy],
    dnsPrefetchControl: [Function: xDnsPrefetchControl],
    expectCt: [Function: expectCt],
    frameguard: [Function: xFrameOptions],
    hidePoweredBy: [Function: xPoweredBy],
    hsts: [Function: strictTransportSecurity],
    ieNoOpen: [Function: xDownloadOptions],
    noSniff: [Function: xContentTypeOptions],
    permittedCrossDomainPolicies: [Function: xPermittedCrossDomainPolicies],
    referrerPolicy: [Function: referrerPolicy],
    xssFilter: [Function: xXssProtection],
    featurePolicy: [Function],
    hpkp: [Function],
    noCache: [Function]
  },
  contentSecurityPolicy: [Function: contentSecurityPolicy],
  dnsPrefetchControl: [Function: xDnsPrefetchControl],
  expectCt: [Function: expectCt],
  frameguard: [Function: xFrameOptions],
  hidePoweredBy: [Function: xPoweredBy],
  hsts: [Function: strictTransportSecurity],
  ieNoOpen: [Function: xDownloadOptions],
  noSniff: [Function: xContentTypeOptions],
  permittedCrossDomainPolicies: [Function: xPermittedCrossDomainPolicies],
  referrerPolicy: [Function: referrerPolicy],
  xssFilter: [Function: xXssProtection],
  featurePolicy: [Function],
  hpkp: [Function],
  noCache: [Function]
}
```

### CODE REVIEW

**Comment by sehrope** [comment]
That's fair.

FYI, I think your point in the main thread (https://github.com/helmetjs/helmet/issues/235#issuecomment-670594860) about not being to do both type and `export = ...` is correct. If you're willing to scrap the named export of the options interface then you can have both the classic function export and the named "helmet" export via a circular one:

```
diff --git a/index.ts b/index.ts
index 81d94e6..63fe7af 100644
--- a/index.ts
+++ b/index.ts
@@ -23,7 +23,7 @@ import xPermittedCrossDomainPolicies, {
 import xPoweredBy from "./middlewares/x-powered-by";
 import xXssProtection from "./middlewares/x-xss-protection";
 
-export interface HelmetOptions {
+interface HelmetOptions {
   contentSecurityPolicy?: MiddlewareOption<ContentSecurityPolicyOptions>;
   dnsPrefetchControl?: MiddlewareOption<XDnsPrefetchControlOptions>;
   expectCt?: MiddlewareOption<ExpectCtOptions>;
@@ -190,5 +190,5 @@ helmet.noCache = () => {
   );
 };
 
-module.exports = helmet;
-export default helmet;
+helmet.helmet = helmet;
+export = helmet;
```

It's still a breaking change though only a TypeScript compile one for users explicitly pulling in the HelmetOptions type:

```typescript
// This breaks:
import { HelmetOptions } from 'helmet';
const opts: HelmetOptions = {
   // options go here
};
```

Direct usage of the middleware function would not change or break:

```typescript
// This continues to work:
import helmet = require('helmet');

// So does this:
import * as helmet from 'helmet';

// And this usage would be validated
helmet({
   // options go here
});

**Comment by EvanHahn** [comment]
Thanks for this. Let's move discussion to #235.

**Comment by vegerot** [comment]
I for one would love this PR, but can understand why the node world as a whole may not be ready to see the light yet :)

**Comment by EvanHahn** [comment]
@vegerot Me too! `helmet@5` may do this.

**Pull request closed without merging**
