### PR TITLE
Improve support for various TypeScript setups, including "nodenext"

### LINKED ISSUE #389: TS1479, helmet typings issue in combination with fastify
In combination with fastify, I get this error. 
https://github.com/fastify/fastify-helmet/issues/210

### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

10.1.0

### Node.js version

16.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

It seems that we get typescript errors, because the typings from helmet are ecmascript and not commonjs

```typescript
uzlopak@Battlestation:~/workspace/nodenext-mvce$ npm run build

> nodenext-test@1.0.0 build
> tsc -p .

node_modules/@fastify/helmet/types/index.d.ts:2:62 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("helmet")' call instead.

2 import helmet, { contentSecurityPolicy, HelmetOptions } from 'helmet';
                                                               ~~~~~~~~


Found 1 error in node_modules/@fastify/helmet/types/index.d.ts:2
```

### Steps to Reproduce

clone https://github.com/Uzlopak/nodenext-mvce/tree/helmet-issue
npm run build

### Expected Behavior

Should not throw

### PR DESCRIPTION
**Pull request by EvanHahn**
Please try this out by running `npm install 'https://evanhahn.com/tape/helmet-6.0.1.tgz'`.

Closes #389 and #391.

When I merge this, I'll make @Uzlopak the author.

### CODE REVIEW

**Comment by Uzlopak** [comment]
Thats strange. I get 

```sh
uzlopak@Battlestation:~/workspace/nodenext-mvce$ npm run build

> nodenext-test@1.0.0 build
> tsc -p .

node_modules/@fastify/helmet/types/index.d.ts:2:18 - error TS2614: Module '"helmet"' has no exported member 'contentSecurityPolicy'. Did you mean to use 'import contentSecurityPolicy from "helmet"' instead?

2 import helmet, { contentSecurityPolicy, HelmetOptions } from 'helmet';
                   ~~~~~~~~~~~~~~~~~~~~~


```

**Comment by Uzlopak** [comment]
i use https://github.com/Uzlopak/nodenext-mvce with the branch helmet-issue

**Comment by EvanHahn** [comment]
How is this pulling in the updated Helmet? Are you doing it manually?

**Comment by Uzlopak** [comment]
Yes. I ran the npm i command you posted above.

Evan Hahn ***@***.***> schrieb am Mi., 15. März 2023, 15:24:

**Comment by yi-fan-song** [comment]
I've got a question for this, can we remove the `"type": "module"` in package.json, it resolves the issue for me, and I'm not seeing why that needs to be set unless this package itself uses module code.

It makes typescript think this package is ES module only, and refuses to resolve the cjs types even when I compile with target commonjs. That only happens when using `moduleResolution: nodenext/node16/node18`

**Comment by EvanHahn** [comment]
@Uzlopak Look for `helmet` in your `node_modules` directory. Is there a `dist/types/` folder there?

@yi-fan-song Are you suggesting we remove `"type": "module"` from Helmet? Or from your own code?

**Comment by yi-fan-song** [comment]
from helmet

**Comment by Uzlopak** [comment]
I dont think that removing the type: module from helmet is useful, as we are moving to esm. But we should be enable cjs for cjs modules. And this is the reason why we have this PR.

That is actually also the reason why it fails in @fastify/helmet, as @fastify/helmet is cjs and not esm.

I will have a look at your changes @EvanHahn and will come back to you asap

**Comment by Uzlopak** [comment]
@EvanHahn 
I am sorry but I got a new Appartment and I have to renovate it. I am totally blocked by this... :-/

**Comment by EvanHahn** [comment]
I just made a few changes. Please try it out with `npm install 'https://evanhahn.com/tape/helmet-6.0.1.tgz'` and let me know what you think.

**Comment by EvanHahn** [comment]
I'm going to merge this soon. Please let me know if this fails to work for you.

**Comment by EvanHahn** [comment]
I intend to make some more updates here but they're not quite ready.

**Comment by EvanHahn** [comment]
This has been published in `helmet@6.1.0`. Thanks to everyone for their help!

**Pull request merged**
