### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by nathannaveen**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks for doing this.

I pin to the major version of these actions (e.g., `@v2`). I read this line in [the GitHub Actions documentation][0]:

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

Given that: are there security benefits to this change?

[0]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by nathannaveen** [comment]
> Thanks for doing this.
> 
> I pin to the major version of these actions (e.g., `@v2`). I read this line in [the GitHub Actions documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses):
> 
> > Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.
> 
> Given that: are there security benefits to this change?

Yes, there aren't any security benefits, none for the existing version, but Github actions will not get any new updates without this.

**Comment by EvanHahn** [comment]
So this would automatically upgrade me from v2 to v3? Is that the idea?

**Comment by nathannaveen** [comment]
> So this would automatically upgrade me from v2 to v3? Is that the idea?

It won't automatically upgrade the version, but it will open a PR for the new version.

**Comment by EvanHahn** [comment]
Thanks. I'll think more about this.

**Comment by nathannaveen** [comment]
> Thanks. I'll think more about this.

Sounds good!

**Comment by Fdawgs** [comment]
To give some more context, we use this in the Fastify and Pino orgs to keep our workflows up to date.
An example PR: https://github.com/fastify/fastify/pull/3736

Knocking it down to a monthly schedule would probably be better, rather than weekly, just because the major bumps don't happen often.

**Pull request closed without merging**
