### PR TITLE
Improvement: Scope module interfaces

### PR DESCRIPTION
**Pull request by victor-enogwe**
## What does this PR do
This PR scopes the helmet interfaces to their respective modules. It also exports the root helmet interfaces - `HelmetOptions`, `MiddlewareFunction` and `MiddlewareOption`

### Motivation and Context
- The current version(`4.1.0`) does not export the root helmet interfaces: `HelmetOptions`, `MiddlewareFunction` and `MiddlewareOption`
- Clean up the middleware interfaces names with module names repeated for each interface declaration.

### Notes
This change would break import styles for interfaces in each module.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (Documentation only changes)
- [ ] Style (Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))
- [x] Refactor (A code change that neither fixes a bug nor adds a feature)
- [ ] Performance (A code change that improves performance)
- [ ] Test (Adding missing tests or correcting existing tests)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm, yarn, docker))
- [ ] CI/CD (Changes to our CI configuration files and scripts (example scopes: Travis, CircleCI, BrowserStack, SauceLabs))
- [ ] Chore (Other changes that don't modify src or test files)
- [ ] Revert (Reverts a previous commit)

### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thank you! I'll take a look at this soon (though probably not for a few days).

**Comment by EvanHahn** [comment]
Thanks again for making this PR. What is the motivation behind doing this? It seems like it's making a breaking types change, which I want to avoid doing this soon after a major version bump.

(Some of the types, such as `MiddlewareFunction` and `MiddlewareOption`, are _deliberately_ private—in other words, I don't think they should be exported.)

**Comment by victor-enogwe** [comment]
The motivation for the PR is to expose the hidden `HelmetOptions` and `MiddlewareOption` interface. 
Also, based on the mono-repo folder structure of the project, scope each interface to its package so there is no repeat of the package name in the interface name. This also makes the interface naming neater and more contextual.

#248 and #235 talks about non-exported Interfaces and helmet@4.1.0-rc.2 says typing issues are resolved, the typings `HelmetOptions` and `MiddlewareOption` are still not exported in helmet@4.1.0-rc.2. 

`MiddlewareFunction` is used only privately and you're right, it can remain private. I think `MiddlewareOption` however, makes the cut to be public as it is a part of the `HelmetOptions` interface and will likely be used in scenarios where the user drills down to the config properties.
e.g. `helmetOptions.frameguard: MiddlewareOption<xFrameOptions.Options> = { ... }`

The example below allows one to use the interfaces but leaves a lot to be desired in naming context.  
> 
> For anybody that was previously importing the `HelmetOptions` interface, e.g. you're assigning the options to a variable rather than directly invoking the middleware function, you can do it by extracting the type from the middleware arg:
> 
> ```ts
> import helmet = require('helmet');
> const opts: Parameters<typeof helmet>[0] = {
>     // strongly typed helmet options go here...
> };
> helmet(opts);
> ```

**Comment by EvanHahn** [comment]
I'm concerned about a couple of things here, both related to breaking changes.

First, expanding Helmet's scope (even a little bit) can have lasting consequences. If I decide I want to restructure MiddlewareOption, for example, I'm not able to do so if I expose it publicly. If I leave it private, we can make that change if it's right for Helmet without having to release a new major version.

Second, it seems like this is a breaking change, and would need to be in Helmet version 5 at the earliest. Is that correct?

**Comment by EvanHahn** [comment]
I just renamed `master` to `main` which caused this PR to be automatically closed. I didn't realize this would happen. My apologies.

However, I think I'm going to leave this closed because I don't think it should be added to Helmet 4. I'll keep this in mind for the next major version, though!

**Pull request closed without merging**
